### ISSUE TITLE
File opening error

### ISSUE THREAD

**Issue by sequoiap** [contagon/SiPANN#12]
I'm running the `examples/filters.py` file from simphony. I get the following error stack:

```
>>> python filters.py
2020-04-30 19:06:19.561668: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-30 19:06:19.573114: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "filters.py", line 16, in <module>
    from simphony.library import ebeam, sipann
  File "C:\Users\user\.conda\envs\simph\lib\site-packages\simphony\library\sipann\__init__.py", line 23, in <module>
    from SiPANN import scee
  File "C:\Users\user\.conda\envs\simph\lib\site-packages\SiPANN\scee.py", line 16, in <module>
    DC_coeffs  = ImportLR(cross_file)
  File "C:\Users\user\.conda\envs\simph\lib\site-packages\SiPANN\import_nn.py", line 259, in __init__
    with open(directory, 'rb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\.conda\\envs\\simph\\lib\\site-packages\\SiPANN\\LR\\DC_coeffs.pkl'
```

**Comment by contagon** [comment]
Fixed. Files hadn't made it into the wheel for some reason.
